### ISSUE TITLE
Remove fields from Array

### ISSUE THREAD

**Issue by frankkulak** [kevlee1/cs4500-a1-part2#5]
Could you please remove the fields from the Array spec? Generally, only methods should be public / part of the interface, and `length` is redundant since `size()` already exists.

**Comment by kevlee1** [comment]
when re-sizing the array for more memory (when adding more elements), wouldn't it be better to have a constant time access to the current length of the array instead of calculating it each time?

I will go ahead and remove the fields in the Array spec though as that is part of the implementation.

**Comment by frankkulak** [comment]
We can still add the field ourselves, and plan to, but it just shouldn't be part of the interface (we're mostly worried about maintaining the `list` field). Thanks for taking care of that for us!
