### ISSUE TITLE
Add include statements

### ISSUE THREAD

**Issue by frankkulak** [kevlee1/cs4500-a1-part2#7]
Please add the following include statements

```
#include <stdio.h>
#include "object.h"
```

`"object.h"` is required for the code to compile, and `<stdio.h>` is nice to have for printing error messages. According to a TA, we are not allowed to include anything that isn't included in your spec.

**Comment by frankkulak** [comment]
Also, please include a `#pragma once` at the beginning

**Comment by kevlee1** [comment]
done!
